### ISSUE TITLE
run error：python setup.py build develop --user， do you give a detail installation？ 

### ISSUE THREAD

**Issue by richardlinxinjian** [KelvinHong/pose-estimation-3d#1]
(pose-esti) PS D:\pose-esti> python setup.py build develop --user
D:\miniconda3\envs\pose-esti\lib\site-packages\setuptools\installer.py:30: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
  SetuptoolsDeprecationWarning,
running build
running build_py
copying alphapose\version.py -> build\lib\alphapose
running develop
D:\miniconda3\envs\pose-esti\lib\site-packages\setuptools\command\easy_install.py:147: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  EasyInstallDeprecationWarning,
D:\miniconda3\envs\pose-esti\lib\site-packages\setuptools\command\install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  setuptools.SetuptoolsDeprecationWarning,
running egg_info
writing alphapose.egg-info\PKG-INFO
writing dependency_links to alphapose.egg-info\dependency_links.txt
writing requirements to alphapose.egg-info\requires.txt
writing top-level names to alphapose.egg-info\top_level.txt
reading manifest file 'alphapose.egg-info\SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'alphapose.egg-info\SOURCES.txt'
D:\miniconda3\envs\pose-esti\lib\site-packages\torch\utils\cpp_extension.py:476: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
  warnings.warn(msg.format('we could not find ninja.'))
running build_ext
Creating c:\users\admin\appdata\roaming\python\python37\site-packages\alphapose.egg-link (link to .)
alphapose 0.5.0+2a1fcc7 is already the active version in easy-install.pth

Installed d:\pose-esti
Processing dependencies for alphapose==0.5.0+2a1fcc7
Searching for halpecocotools
Reading https://pypi.tuna.tsinghua.edu.cn/simple/halpecocotools/
D:\miniconda3\envs\pose-esti\lib\site-packages\pkg_resources\__init__.py:126: PkgResourcesDeprecationWarning:  is an invalid version and will not be supported in a future release
  PkgResourcesDeprecationWarning,
Downloading https://pypi.tuna.tsinghua.edu.cn/packages/f9/b0/f2e783a29a30cf0e66e3bbc45cdc4da6e9214bc21f4df948ee9a7d79764e/halpecocotools-0.0.0.tar.gz#sha256=8355964f7d14e69b2a555be7e116eae8979ec2a04f0eef16d140b38d04f933eb
Best match: halpecocotools 0.0.0
Processing halpecocotools-0.0.0.tar.gz
Writing C:\Users\Admin\AppData\Local\Temp\easy_install-uqk3wcn8\halpecocotools-0.0.0\setup.cfg
Running halpecocotools-0.0.0\setup.py -q bdist_egg --dist-dir C:\Users\Admin\AppData\Local\Temp\easy_install-uqk3wcn8\halpecocotools-0.0.0\egg-dist-tmp-yvmxgcr4
warning: no files found matching '*.pxd'
warning: no files found matching '*.pyx'
D:\miniconda3\envs\pose-esti\lib\site-packages\setuptools\command\install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  setuptools.SetuptoolsDeprecationWarning,
D:\miniconda3\envs\pose-esti\lib\site-packages\Cython\Compiler\Main.py:384: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: C:\Users\Admin\AppData\Local\Temp\easy_install-uqk3wcn8\halpecocotools-0.0.0\halpecocotools\_mask.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
maskApi.c
c1: fatal error C1083: 无法打开源文件: “../common/maskApi.c”: No such file or directory
error: Setup script exited with error: command 'D:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2

**Comment by KelvinHong** [comment]
Hi, can you share your Python version, and I guess you're using Windows right?

**Comment by KelvinHong** [comment]
I have updated the README file, added some more specifications. Can you install the program again and see whether it is working?

**Comment by richardlinxinjian** [comment]
yes，in windows OS.
python version：3.7

--------------原始邮件--------------
发件人："KelvinHong ***@***.***&gt;;
发送时间：2023年9月5日(星期二) 上午10:56
收件人："KelvinHong/pose-estimation-3d" ***@***.***&gt;;
抄送："richardlinxinjian ***@***.***&gt;;"Author ***@***.***&gt;;
主题：Re: [KelvinHong/pose-estimation-3d] run error：python setup.py build develop --user， do you give a detail installation？  (Issue #1)
-----------------------------------

 

 
Hi, can you share your Python version, and I guess you're using Windows right?

**Comment by richardlinxinjian** [comment]
I will try it later.
Thank you.

--------------原始邮件--------------
发件人："KelvinHong ***@***.***&gt;;
发送时间：2023年9月5日(星期二) 中午11:33
收件人："KelvinHong/pose-estimation-3d" ***@***.***&gt;;
抄送："richardlinxinjian ***@***.***&gt;;"Author ***@***.***&gt;;
主题：Re: [KelvinHong/pose-estimation-3d] run error：python setup.py build develop --user， do you give a detail installation？  (Issue #1)
-----------------------------------

 

 
I have updated the README file, added some more specifications. Can you install the program again and see whether it is working?

**Comment by KelvinHong** [comment]
You're welcome! Consider install Python 3.9, since Blender software in this program is bundled with version 3.9 of Python. Feel free to ping me again if you have other issue.

**Comment by richardlinxinjian** [comment]
&nbsp;this time，I create a new conda env with python 3.9 on windows 10.
But, the result is same.

Detail error info:
---------------------------------------
(pose-esti) D:\pose-esti&gt;python setup.py build develop --user
D:\miniconda3\envs\pose-esti\lib\site-packages\setuptools\__init__.py:84: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
!!


&nbsp; &nbsp; &nbsp; &nbsp; ********************************************************************************
&nbsp; &nbsp; &nbsp; &nbsp; Requirements should be satisfied by a PEP 517 installer.
&nbsp; &nbsp; &nbsp; &nbsp; If you are using pip, you can try `pip install --use-pep517`.
&nbsp; &nbsp; &nbsp; &nbsp; ********************************************************************************


!!
&nbsp; dist.fetch_build_eggs(dist.setup_requires)
running build
running build_py
copying alphapose\version.py -&gt; build\lib\alphapose
running develop
D:\miniconda3\envs\pose-esti\lib\site-packages\setuptools\command\develop.py:40: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!


&nbsp; &nbsp; &nbsp; &nbsp; ********************************************************************************
&nbsp; &nbsp; &nbsp; &nbsp; Please avoid running ``setup.py`` and ``easy_install``.
&nbsp; &nbsp; &nbsp; &nbsp; Instead, use pypa/build, pypa/installer or other
&nbsp; &nbsp; &nbsp; &nbsp; standards-based tools.


&nbsp; &nbsp; &nbsp; &nbsp; See https://github.com/pypa/setuptools/issues/917 for details.
&nbsp; &nbsp; &nbsp; &nbsp; ********************************************************************************


!!
&nbsp; easy_install.initialize_options(self)
D:\miniconda3\envs\pose-esti\lib\site-packages\setuptools\_distutils\cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!


&nbsp; &nbsp; &nbsp; &nbsp; ********************************************************************************
&nbsp; &nbsp; &nbsp; &nbsp; Please avoid running ``setup.py`` directly.
&nbsp; &nbsp; &nbsp; &nbsp; Instead, use pypa/build, pypa/installer or other
&nbsp; &nbsp; &nbsp; &nbsp; standards-based tools.


&nbsp; &nbsp; &nbsp; &nbsp; See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
&nbsp; &nbsp; &nbsp; &nbsp; ********************************************************************************


!!
&nbsp; self.initialize_options()
running egg_info
writing alphapose.egg-info\PKG-INFO
writing dependency_links to alphapose.egg-info\dependency_links.txt
writing requirements to alphapose.egg-info\requires.txt
writing top-level names to alphapose.egg-info\top_level.txt
reading manifest file 'alphapose.egg-info\SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'alphapose.egg-info\SOURCES.txt'
D:\miniconda3\envs\pose-esti\lib\site-packages\torch\utils\cpp_extension.py:476: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
&nbsp; warnings.warn(msg.format('we could not find ninja.'))
running build_ext
Creating c:\users\admin\appdata\roaming\python\python39\site-packages\alphapose.egg-link (link to .)
alphapose 0.5.0+2a1fcc7 is already the active version in easy-install.pth


Installed d:\pose-esti
Processing dependencies for alphapose==0.5.0+2a1fcc7
Searching for halpecocotools
Reading https://pypi.tuna.tsinghua.edu.cn/simple/halpecocotools/
Downloading https://pypi.tuna.tsinghua.edu.cn/packages/f9/b0/f2e783a29a30cf0e66e3bbc45cdc4da6e9214bc21f4df948ee9a7d79764e/halpecocotools-0.0.0.tar.gz#sha256=8355964f7d14e69b2a555be7e116eae8979ec2a04f0eef16d140b38d04f933eb
Best match: halpecocotools 0.0.0
Processing halpecocotools-0.0.0.tar.gz
Writing C:\Users\Admin\AppData\Local\Temp\easy_install-0a80516s\halpecocotools-0.0.0\setup.cfg
Running halpecocotools-0.0.0\setup.py -q bdist_egg --dist-dir C:\Users\Admin\AppData\Local\Temp\easy_install-0a80516s\halpecocotools-0.0.0\egg-dist-tmp-dp4vk6ls
warning: no files found matching '*.pxd'
warning: no files found matching '*.pyx'
D:\miniconda3\envs\pose-esti\lib\site-packages\setuptools\_distutils\cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!


&nbsp; &nbsp; &nbsp; &nbsp; ********************************************************************************
&nbsp; &nbsp; &nbsp; &nbsp; Please avoid running ``setup.py`` directly.
&nbsp; &nbsp; &nbsp; &nbsp; Instead, use pypa/build, pypa/installer or other
&nbsp; &nbsp; &nbsp; &nbsp; standards-based tools.


&nbsp; &nbsp; &nbsp; &nbsp; See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
&nbsp; &nbsp; &nbsp; &nbsp; ********************************************************************************


!!
&nbsp; self.initialize_options()
D:\miniconda3\envs\pose-esti\lib\site-packages\Cython\Compiler\Main.py:384: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: C:\Users\Admin\AppData\Local\Temp\easy_install-0a80516s\halpecocotools-0.0.0\halpecocotools\_mask.pyx
&nbsp; tree = Parsing.p_module(s, pxd, full_module_name)
maskApi.c
c1: fatal error C1083: 无法打开源文件: “../common/maskApi.c”: No such file or directory
error: Setup script exited with error: command 'D:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2

&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Tue, Sep 5, 2023 11:48 AM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [KelvinHong/pose-estimation-3d] run error：python setup.py build develop --user， do you give a detail installation？  (Issue #1)

&nbsp;



 
You're welcome! Consider install Python 3.9, since Blender software in this program is bundled with version 3.9 of Python. Feel free to ping me again if you have other issue.

**Comment by KelvinHong** [comment]
Hi, I could not reproduce the error myself. But what I could suggest is to not use conda (I haven't try it before, only tried virtualenv myself), so you might need to do the same as using virtual environment only. Furthermore, you can try installing Visual Studio 2019 into your machine and reinstall this program again.

**Comment by KelvinHong** [comment]
Since there is no response, I assume the issue is resolved. You can reopen again if still not able to proceed.
